### ISSUE TITLE
Add support for running within a single git repository

### ISSUE THREAD

**Issue by stephenh** [badele/gitcheck#14]
Thanks for gitcheck, it's awesome!

If I get super-used to the gitcheck output for my list of N repositories, I'd like to be able to drill into just one (cd repo_i_care_about_now), run gitcheck again, and see the same very nicely formatted results.

Seems like it shouldn't be too hard to add an "am I running in a git repo" check, assuming you think that's an acceptable usage.

**Comment by markusweb** [comment]
Yes please!
i tried to run gitcheck.py on my test repo.
as i am running in git 1.7.x i had no git -C xxx option. after i changed gitExec gitcheck works.
so it would be great to have this either as a command-line option. then both could be done:

1) like stephenh asked to have the check only in one repo
2) to add a switch or better to check git version and remove the -C xx option in gitExec

markus

**Comment by badele** [comment]
You can check only one project with -d feature. What your distribution use with git 1.7 ? Actually, you maybe use the debian wheezy based version ?  In my archlinux system, i use the 2.4.2 git version.

**Comment by tessus** [comment]
It also works running gitcheck within the repository's directory.

**Comment by badele** [comment]
effectively, @tessus  is right, this feature allready exist. I closee this issue
