### ISSUE TITLE
Only shows develop branches on Ubuntu 14.04

### ISSUE THREAD

**Issue by vdesaraju** [badele/gitcheck#16]
Thank you for making this script - it has been very helpful. However, I just switched from Ubuntu 12.04 to 14.04 and noticed one big issue: it seems to only show repositories that are on develop branches. I checked out a feature branch for one repo and it disappeared from the gitcheck list. I switched back to develop, and it reappeared. The same thing happened when I checked out the master branch too. One of my colleagues also confirmed that he is seeing the same thing, so I don't think it is specific to my setup.

I hope you can look into this soon. I do not know what other information I can provide to help debug this, but let me know if there is anything I should try.

**Comment by badele** [comment]
Hi,

i'm sorry, i'm not a Ubuntu user, i'm use the Archlinux distribution. Your repository is public or private. If is public, can you send me the URL for analysing the problem ? And if i understand, gitcheck now work only with branch and not with mainstream ?

Can you send me more detail and samples for i understand a problem ?

Thanks

**Comment by vdesaraju** [comment]
Unfortunately the repository is private, so I cannot send a url for it. Maybe this example will help?

If I have a repository called test_repo that is currently on the develop branch and I run `gitcheck`, I get this as expected:
test_repo/develop

However, if I change the branch by running `git checkout otherbranch` and then run `gitcheck`, I see no output. If I do `git checkout master` followed by `gitcheck`, it again shows nothing. If I then do `git checkout develop` followed by `gitcheck` it shows
test_repo/develop

However, what is very strange is that this does not happen for all repositories. I have this problem with repositories cloned from our private GitLab server but have no problems with repositories cloned from GitHub... but I cannot figure out what the difference is between them. It does work with both on Ubuntu 12.04 with an older version of git and gitcheck, so I do not think it is entirely a problem with the repositories.

**Comment by badele** [comment]
@vdesaraju I added a debug message, can you execute the gitcheck with --debug option ? And can you send me this result here (if not privacy datas) or send me a result in private message bruno@adele.im

**Comment by vdesaraju** [comment]
I just updated to the latest version and this issue seems to be resolved now. Thanks!

**Comment by badele** [comment]
Well, this is a good news ! :) Thanks for your issue report and your feedback
