### ISSUE TITLE
Multiple dirs

### ISSUE THREAD

**Issue by z-engine** [badele/gitcheck#31]
What do you think about the possibility to add param something like a `--from-list file`
where the file is:
```bash
/home/user/data/projects
/home/user/.confgis/dotfiles
/home/user/.configs/sublime-text-3/Packages/User
/home/user/.vim
/mount/point/some_repo
/mount/point/another_repo
```
Scan `/home` takes a lot of time, not to mention the `Scan /` and flag `--maxdepth` will not help here.  
...or at least`-d /path/to/repo -d /path/to/another/repo`. Now `gitcheck` with `-d` takes only last dir 

Of course, I can make a script 
```bash
for i in `cat list`;do gitcheck -d $i;done
```
and i can even run it in parallel with `xargs` or `parallel`but it would be nice if it was part of `gitcheck`

**Comment by glennular** [comment]
PR to support the multiple -d option

**Comment by glennular** [comment]
@z-engine  the PR has been merged to master, give it a try. Let us know what you think.
